export const FETCH_WORKFLOW_TEMPLATES_IN_PROGRESS = 'FETCH_WORKFLOW_TEMPLATES_IN_PROGRESS'
export const FETCH_WORKFLOW_TEMPLATES_COMPLETED = 'FETCH_WORKFLOW_TEMPLATES_COMPLETED'
export const FETCH_WORKFLOW_TEMPLATES_FAILED = 'FETCH_WORKFLOW_TEMPLATES_FAILED'

export const FETCH_WORKFLOW_TRANSITIONS_IN_PROGRESS = 'FETCH_WORKFLOW_TRANSITIONS_IN_PROGRESS'
export const FETCH_WORKFLOW_TRANSITIONS_COMPLETED = 'FETCH_WORKFLOW_TRANSITIONS_COMPLETED'
export const FETCH_WORKFLOW_TRANSITIONS_FAILED = 'FETCH_WORKFLOW_TRANSITIONS_FAILED'

export const FETCH_WORKFLOW_ACTIONS_IN_PROGRESS = 'FETCH_WORKFLOW_ACTIONS_IN_PROGRESS'
export const FETCH_WORKFLOW_ACTIONS_COMPLETED = 'FETCH_WORKFLOW_ACTIONS_COMPLETED'
export const FETCH_WORKFLOW_ACTIONS_FAILED = 'FETCH_WORKFLOW_ACTIONS_FAILED'

export const UPDATE_TRANSITION_IN_PROGRESS = 'UPDATE_TRANSITION_IN_PROGRESS'
export const UPDATE_TRANSITION_COMPLETED = 'UPDATE_TRANSITION_COMPLETED'
export const UPDATE_TRANSITION_FAILED = 'UPDATE_TRANSITION_FAILED'

export const CREATE_TRANSITIONS_IN_PROGRESS = 'CREATE_TRANSITIONS_IN_PROGRESS'
export const CREATE_TRANSITIONS_COMPLETED = 'CREATE_TRANSITIONS_COMPLETED'
export const CREATE_TRANSITIONS_FAILED = 'CREATE_TRANSITIONS_FAILED'